### ISSUE TITLE
No lootables, nor fish

### ISSUE THREAD

**Issue by ghost** [benda95280/MyFish#1]
I enabled this plugin for my server and it seems to work, but everytime I throw the hook in water, no bubbles appear to say that I've caught something. It simply floats and does nothing, but floating.

**Comment by benda95280** [comment]
Have you try to wait 2 real minutes ?

**Comment by reyyoga** [comment]
How to Custom fish?

**Comment by benda95280** [comment]
? Sorry does this question have something to see with the issue ?
