### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by MonoAdrian23** [benda95280/MyFish#10]
I have Teaspoon and there is Fishing implemented.
When i Install youre Plugin, it doenst Override Teaspoon.
I have Fishing in Teaspoon set to false but Fishing Rods doenst Work.
When i Set to true, it use Teaspoon Fishing system
How can i fix this?
Teaspoon 1.2.0
Pocketmine 3.15.1
Myfish Dev 17

**Comment by benda95280** [comment]
Heyllo,
Sorry, i've removed TeaSpoon on my side.
I'll not be able to give you any support, as i try to avoid it, and have separated plugins to each of my needs.

**Comment by MonoAdrian23** [comment]
Oh man this is Not so good.
Youre Plugin was the best Fishing Plugin ever.
Teaspoons Fishing Loot table is broken and youre Plugin was a good alternative for it.

**Comment by benda95280** [comment]
Try to see if without teaspoon it works ... If yes ... Try to avoid teaspoon, and find a plugin for each of your need :)
