### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by brokiem** [benda95280/MyFish#2]
when someone drop the fishing rod, the hook not gone 

how to reproduce:
fish and drop [Q] the fishing rod

hooh sorry my english bad 
![a  aa](https://user-images.githubusercontent.com/61258338/85197299-be32b980-b312-11ea-809c-41858572c718.PNG)

**Comment by benda95280** [comment]
Last Update should fix it, could you try ?

**Comment by brokiem** [comment]
yes
