### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by MonoAdrian23** [benda95280/MyFish#4]
I am using the Plugin Enchant ShopUi
And everytime i try to enchant luck of the sea or lure, it says "please hold a valid Item in youre hand"
Fishing Rod is also not compatible with that.
MyFish Dev 3
Pocketmine 3.12.6
Thanks for youre help

**Comment by benda95280** [comment]
Could you send me the link of GH for the plugin you'r using ?

**Comment by MonoAdrian23** [comment]
https://github.com/UnknownOre/EnchantShopUI

**Comment by benda95280** [comment]
Could you show/send me the content of your Shop.yml ?

**Comment by MonoAdrian23** [comment]
- name: "Glück des Meeres"
  enchantment: luck_of_the_sea
  price: 5000
  max-level: 3
  incompatible-enchantments: []
- name: "Köder"
  enchantment: lure
  price: 1000
  max-level: 3
  incompatible-enchantments: []

**Comment by MonoAdrian23** [comment]
version: "0.5"

#send EnchantUI to the player when he interacts with the Enchanting-table
enchanting-table: true

#EnchantUI version 0.6
Title: "§cEnchantment Shop"
Button: "§3{NAME} §a{PRICE}$"
slider-title: "§5Level"
messages:
  thanks: "§athank you for using Enchantment Shop"
  label: "§eYou will pay {PRICE}$ per level"
  not-enough-money: "§cyou don't have enough money!"
  paid-success: "§aYou bought {NAME} level {LEVEL} for {PRICE}$"
  hold-item: "§cPlease hold an item that can be enchanted"
  no-perm: "§cYou don't have permission to use this command"
  incompatible-enchantment:
  
#WARNING: Use only Enchantment ID at incompatible-enchantments example [1,10,13]
shop:
- name: "Fire Protection"
  enchantment: fire_protection
  price: 100
  max-level: 2
  incompatible-enchantments: []
- name: "Protection"
  enchantment: 1
  price: 100
  max-level: 3
  incompatible-enchantments: []
- name: "Glück des Meeres"
  enchantment: luck_of_the_sea
  price: 5000
  max-level: 3
  incompatible-enchantments: []
- name: "Köder"
  enchantment: lure
  price: 1000
  max-level: 3
  incompatible-enchantments: []
...

**Comment by benda95280** [comment]
Could you try with lastest version ?
