### ISSUE TITLE
Server Crash 1.16 

### ISSUE THREAD

**Issue by MonoAdrian23** [benda95280/MyFish#5]
PocketMine-MP Crash Dump Wed Jul 1 11:03:42 +07 2020

Error: file_put_contents(/home/minecraft/plugin_data/Fishing/level.yml): failed to open stream: No such file or directory
File: src/pocketmine/utils/Config
Line: 241
Type: ErrorException

A PLUGIN WAS INVOLVED IN THIS CRASH
BAD PLUGIN: Fishing v0.3

Code:

Backtrace:
#0 (): pocketmine\utils\Utils::errorExceptionHandler(integer 2, string[114] file_put_contents(/home/minecraft/plugin_data/Fishing/level.yml): failed to open, string[70] phar:///home/minecraft/pocketmine.phar/src/pocketmine/utils/Config.php, integer 241, array[1])
#1 src/pocketmine/utils/Config(241): file_put_contents(string[45] /home/minecraft/plugin_data/Fishing/level.yml, string[79] ---.logischerdaum: 49.viewablefiber98: 6.itzcookietv: 3.mandarinegustav: 5.....)
#2 plugins/MyFish.phar/src/Fishing/utils/FishingLevel(63): pocketmine\utils\Config->save()
#3 plugins/MyFish.phar/src/Fishing/utils/FishingLevel(26): Fishing\utils\FishingLevel::saveConfig()
#4 src/pocketmine/scheduler/TaskHandler(134): class@anonymousphar:///home/minecraft/plugins/MyFish.phar/src/Fishing/utils/FishingLevel.php0x7f4fdc98c29b->onRun(integer 1606801)
#5 src/pocketmine/scheduler/TaskScheduler(176): pocketmine\scheduler\TaskHandler->run(integer 1606801)
#6 src/pocketmine/plugin/PluginManager(654): pocketmine\scheduler\TaskScheduler->mainThreadHeartbeat(integer 1606801)
#7 src/pocketmine/Server(2388): pocketmine\plugin\PluginManager->tickSchedulers(integer 1606801)
#8 src/pocketmine/Server(2151): pocketmine\Server->tick()
#9 src/pocketmine/Server(1991): pocketmine\Server->tickProcessor()
#10 src/pocketmine/Server(1585): pocketmine\Server->start()
#11 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[16] /home/minecraft/, string[24] /home/minecraft/plugins/)
#12 src/pocketmine/PocketMine(296): pocketmine\server()
#13 (11): require(string[68] phar:///home/minecraft/pocketmine.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 3.13.0 [Protocol 390]
Git commit: 323d96d5c19c518aa168fcace2fd2f2f723cc7dc
uname -a: Linux 8d10e7954726 5.4.0-0.bpo.4-amd64 #1 SMP Debian 5.4.19-1~bpo10+1 (2020-03-09) x86_64
PHP Version: 7.3.16
Zend version: 3.3.16
OS : Linux, linux
Composer libraries: 
- adhocore/json-comment 0.1.0@8448076039389f558f39ad0553aab87db3f81614
- ocramius/package-versions 1.5.1@1d32342b8c1eb27353c8887c366147b4c2da673c
- pocketmine/binaryutils 0.1.11@e8cb65db1b7998eebb739b124f2a989fe87366eb
- pocketmine/callback-validator 1.0.1@4aef6bb25f97d0b830ba0b4f66834b1a9c86fc9a
- pocketmine/classloader 0.1.0@4ccdb30e48f030bfcad04bb0a208d198ec631993
- pocketmine/log 0.2.0@e59bedb5d4bbeb9a26647cb7c367cb2fa72addfa
- pocketmine/log-pthreads 0.1.0@9bbcef398b01487ab47c234a6a7054722abbe067
- pocketmine/math 0.2.4@b1c28b236df8b795d7b06cf8421f9962b12ac410
- pocketmine/nbt 0.2.14@b31dca98443328c4bab76dc1b84c1473c79be20e
- pocketmine/raklib 0.12.8@9fea763ffc922db083e4528d4acd0b13d0ea83a4
- pocketmine/snooze 0.1.2@88420da3d9335dbcb3ee2decfd5e5453d057dcdf
- pocketmine/spl 0.4.1@ff0579a0be41bbe65d3637607715c0f87728a838
- doctrine/instantiator 1.3.1@f350df0268e904597e3bd9c4685c53e0e333feea
- myclabs/deep-copy 1.9.5@b2c28789e80a97badd14145fda39b545d83ca3ef
- phar-io/manifest 1.0.3@7761fcacf03b4d4f16e7ccb606d4879ca431fcf4
- phar-io/version 2.0.1@45a2ec53a73c70ce41d55cedef9063630abaf1b6
- phpdocumentor/reflection-common 2.1.0@6568f4687e5b41b054365f9ae03fcb1ed5f2069b
- phpdocumentor/reflection-docblock 5.1.0@cd72d394ca794d3466a3b2fc09d5a6c1dc86b47e
- phpdocumentor/type-resolver 1.1.0@7462d5f123dfc080dfdf26897032a6513644fc95
- phpspec/prophecy v1.10.3@451c3cd1418cf640de218914901e51b064abb093
- phpstan/phpstan 0.12.25@9619551d68b2d4c0d681a8df73f3c847c798ee64
- phpstan/phpstan-phpunit 0.12.11@ab783a8ea634ea23305a8818c4750603e714489b
- phpstan/phpstan-strict-rules 0.12.2@a670a59aff7cf96f75d21b974860ada10e25b2ee
- phpunit/php-code-coverage 7.0.10@f1884187926fbb755a9aaf0b3836ad3165b478bf
- phpunit/php-file-iterator 2.0.2@050bedf145a257b1ff02746c31894800e5122946
- phpunit/php-text-template 1.2.1@31f8b717e51d9a2afca6c9f046f5d69fc27c8686
- phpunit/php-timer 2.1.2@1038454804406b0b5f5f520358e78c1c2f71501e
- phpunit/php-token-stream 3.1.1@995192df77f63a59e47f025390d2d1fdf8f425ff
- phpunit/phpunit 8.5.5@63dda3b212a0025d380a745f91bdb4d8c985adb7
- sebastian/code-unit-reverse-lookup 1.0.1@4419fcdb5eabb9caa61a27c7a1db532a6b55dd18
- sebastian/comparator 3.0.2@5de4fc177adf9bce8df98d8d141a7559d7ccf6da
- sebastian/diff 3.0.2@720fcc7e9b5cf384ea68d9d930d480907a0c1a29
- sebastian/environment 4.2.3@464c90d7bdf5ad4e8a6aea15c091fec0603d4368
- sebastian/exporter 3.1.2@68609e1261d215ea5b21b7987539cbfbe156ec3e
- sebastian/global-state 3.0.0@edf8a461cf1d4005f19fb0b6b8b95a9f7fa0adc4
- sebastian/object-enumerator 3.0.3@7cfd9e65d11ffb5af41198476395774d4c8a84c5
- sebastian/object-reflector 1.1.1@773f97c67f28de00d397be301821b06708fca0be
- sebastian/recursion-context 3.0.0@5b0cd723502bac3b006cbf3dbf7a1e3fcefe4fa8
- sebastian/resource-operations 2.0.1@4d7a795d35b889bf80a0cc04e08d77cedfa917a9
- sebastian/type 1.1.3@3aaaa15fa71d27650d62a948be022fe3b48541a3
- sebastian/version 2.0.1@99732be0ddb3361e16ad77b68ba41efc8e979019
- symfony/polyfill-ctype v1.17.0@e94c8b1bbe2bc77507a1056cdb06451c75b427f9
- theseer/tokenizer 1.1.3@11336f6f84e16a720dae9d8e6ed5019efa85a0f9
- webmozart/assert 1.8.0@ab2cb0b3b559010b75981b1bdce728da3ee90ad6
- pocketmine/pocketmine-mp 3.13.0@323d96d5c19c518aa168fcace2fd2f2f723cc7dc

**Comment by benda95280** [comment]
Dear MonoAdrian23,

I've just take a look, file is automaticaly created on my side (Windows PMMP Server, 3.14)
Is the 'Fishing' folder or level.yml file existing ?

A new update will be pushed with some fixe and feature too, and i hope to release it today.

**Comment by MonoAdrian23** [comment]
Yes level.yml is existing

**Comment by benda95280** [comment]
Is level file exactly here ? :
/home/minecraft/plugin_data/Fishing/level.yml
With the same name (Upper/lower case ?)

If yes, are you still having the issue after a restart of the server ?

**Comment by MonoAdrian23** [comment]
No
It works now, i test it a few times

**Comment by MonoAdrian23** [comment]
But in Latest Dev 11
My language has changed xd

**Comment by benda95280** [comment]
I'm happy to read it works now :)
About the language, i've finished new features, and i'm going to add a config file for the language, update on the way

**Comment by MonoAdrian23** [comment]
And at next
No more loot
IT says that bites a fish in another language but there is no Loot

**Comment by benda95280** [comment]
Next update will come today (Current language is french :smile: )
You will have more information on features in that plugin, and have ability to set your own language :)

**Comment by MonoAdrian23** [comment]
Yes German language is my dream

**Comment by MonoAdrian23** [comment]
And thanks for youre hard Work at this plugin! Its very useful

**Comment by benda95280** [comment]
New update are out, need some testing and corrections, but should works.

**Comment by MonoAdrian23** [comment]
Yes works great
Only a fish bites text is not configurable
Italy xd

**Comment by benda95280** [comment]
Will try to put this text in config file

**Comment by benda95280** [comment]
I close this issue, has it seems to be resolved.
