### ISSUE TITLE
Player cant fish anymore at lvl 3

### ISSUE THREAD

**Issue by Willoxey** [benda95280/MyFish#7]
Pmmp version: 3.14.2
Plugin version: 0.4
PHP Version: 7.3.14

Description: When you get level 3 at fishing. You get this error even if it's day. "You cant fish with this lvl at night..."(translated from french). Tried already setting the time with /time set day, etc... but keep getting that error.

**Comment by benda95280** [comment]
Could you try again ?
ReadMe Has been updated too, thanks
