### ISSUE TITLE
How To Use?

### ISSUE THREAD

**Issue by HanifWadowsky** [benda95280/MyFish#8]
need more plugins?

**Comment by Willoxey** [comment]
No.
Just download a fresh copy of the plugin and drag it into plugins folder.
Restart the server and you are done.

Although there is an addon anyway for ScoreHud. But it's optional!

**Comment by HanifWadowsky** [comment]
what is?

Ma ligne a cassée, mon niveau est trop faible.

how to raise the level?

**Comment by benda95280** [comment]
Sorry, i'm french :)
'My line broke, my level is too low.' is because you'r trying to send your hook too far.
See ReadMe (The distance (Force) of the hook change beased on your leve)
